### PR TITLE
Allow user defined id when adding dashboards & visualizations

### PR DESCRIPTION
**Pull request by d-mo**

### CODE REVIEW

**Comment by d-mo** [comment]
Thanks for merging this! Do you have any plans for releasing the next version on pypi? I'm working on a project that depends on this and unfortunately it's still quite messy in Python to add dependencies from github repos.

**Comment by harabchuk** [comment]
You are welcome ) Thanks for contribution
I am rather new to pypi, what should I change/add?

**Comment by d-mo** [comment]
Just bump up the version number and publish a new release that includes the latest code. The recommended way is to do it using twine https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

**Comment by harabchuk** [comment]
Got it. Sure I will release a new version now

**Comment by harabchuk** [comment]
Done. The version 0.1.1 is released :)

**Pull request merged**
